apiVersion: v2
name: osbuilder
description: A Helm chart for osbuilder
icon: 
type: application
home: https://kairos.io/
maintainers:
- name: Ettore Di Giacinto
  email: mudler@kairos.io

version: 0.4.0-jbalonso1
appVersion: "v0.4.0"
